---
sudo: true

language: java

jdk: oraclejdk8

before_install:
   - sudo apt-get install rpm

script:
   - mvn clean install -B
   - mkdir -p ~/rpmbuild/SOURCES
   - cp target/*jar ~/rpmbuild/SOURCES
   - export VERSION=$(sed -n '0,/^.*<version>\(.*\)<\/version>.*$/s//\1/p' pom.xml)
   - rpmbuild -ba paella-opencast.spec

after_success:
   - curl -i -u pkg:3d37ba94-a305-4185-8989-861e2491fc https://pkg.opencast.org/upload \
     -F file=@rpmbuild/RPMS/x86_64/paella-opencast-${VERSION}-1.x86_64.rpm
