---
sudo: true

language: java

jdk: oraclejdk8

before_install:
   - sudo apt-get install rpm

script:
   - mvn clean install -B
   - rpmdev-setuptree
   - cp target/*jar ~/rpmbuild/SOURCES
   - export VERSION=$(sed -n '0,/^.*<version>\(.*\)<\/version>.*$/s//\1/p' pom.xml)
   - rpmbuild -ba paella-opencast.spec

after_success:
   - find ~/rpmbuild/
